### ISSUE TITLE
The project does not appear on solana.com/ecosystem

### ISSUE THREAD

**Issue by LeRoYGo** [solana-labs/ecosystem#407]
My project was added to the repository, but it does not show up on solana.com/ecosystem. What could be the reason?

**Comment by Paradise525** [comment]
same question

**Comment by goodgamesguild** [comment]
same question for me...

**Comment by SynergyLand** [comment]
Yeah, Im also waiting...

**Comment by teampurity** [comment]
Our project actually errored when merging, so we fixed it. That is here https://github.com/solana-labs/ecosystem/pull/410

We are a bit nervous with how long it's taking to merge, though.
