### ISSUE TITLE
PR not being merged for new project

### ISSUE THREAD

**Issue by genemergent** [solana-labs/ecosystem#597]
This PR still hasn't been merged, do we need to contact someone directly?

https://github.com/solana-labs/ecosystem/pull/533

**Comment by tetmin** [comment]
any plans to look at this?

**Comment by genemergent** [comment]
Hi, any plans to look at this?

**Comment by genemergent** [comment]
Is this repo still being managed & used to update the ecosystem? Do I need to contact someone direct to talk about getting a PR merged? If so, who do I need to contact please?

**Comment by genemergent** [comment]
Anyone?
