### ISSUE TITLE
PR Problem

### ISSUE THREAD

**Issue by nftstorestudio** [solana-labs/ecosystem#678]
Hi ,

I upload PNG and MD file and after that I want to PR finally I got error in Some checks were not successful at Continuous Integration / prettier (pull_request) Failing . Why ? As below error ...

no changes added to commit
No files added to commit
remote: Permission to solana-labs/ecosystem.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/solana-labs/ecosystem/': The requested URL returned error: 403

**Comment by amit-btc** [comment]
Yeah I am seeing the same error, i think its bad merge from previous PR.

**Comment by nftstorestudio** [comment]
@amit-btc hi , how to solve this case before ? I tried to many times to PR from my master to solana master . As far as I see , some project did it as I said . Do you have any recommend ?
