### ISSUE TITLE
Pull request merged and okay, but project not showing up on solana.com/ecosystem website

### ISSUE THREAD

**Issue by swts** [solana-labs/ecosystem#679]
Hello,

I'm having an issue about a PR I created and that was merged.

Here's the comment: Merged #552 into master.
And here's the link to the PR: https://github.com/solana-labs/ecosystem/pull/552

I'm wondering why isn't the project showing up on the website?

Thank you in advance for answering!

**Comment by WhiteElephantEco** [comment]
we had ours merged 2 weeks ago and has not shown up on their website. i dont think they are updating it anymore.

**Comment by swts** [comment]
The thing is, our community is asking why "lesser", less transparent and less popular project are listed, and some of the better ones are not.

Does not seem right IMO

**Comment by WhiteElephantEco** [comment]
they like to list nft more than spl and other product. look at the ecosystem

**Comment by teampurity** [comment]
We (https://sol100.io) were merged and also not displayed on /ecosystem. We're hopeful that this is a temporary issue. Otherwise there is faulty knee jerk due diligence is being run by a panel of people newer to the Internet, or a single central ruling authority happening. Being excluded from the ecosystem website is a slap in the face to hard working developers supporting and building on the Solana ecosystem.

**Comment by SolarDexOfficial** [comment]
Anyone here's issues get resolved? We submitted everything about a week ago and nothing

**Comment by swts** [comment]
I don't really know man,

It seems less legit P&D projects are on that list, and some of the project that deserve to be there arent....

**Comment by SolarDexOfficial** [comment]
Dang man - out of curiosity what's your project? Looking for partnerships (twitter - @solar_dex)

**Comment by WhiteElephantEco** [comment]
i checked the ecosystem and the file the last listed on the website was 2
months ago. It would be nice if we get listed too since it would help in
our presale and pooling. at this rate with very few launchpad in solana and
nft gets prioritised listed than legit projects, wangmi. hahaha!

**Comment by WhiteElephantEco** [comment]
hey we will launch a launchpad. let me know if you want to launch in our
launchpad.

**Comment by SolarDexOfficial** [comment]
When do you release? Needing a launchpad service in 2 weeks

**Comment by WhiteElephantEco** [comment]
hoping to release next week for ido, staking and presale. putting our
effort into that right now.

**Comment by SolarDexOfficial** [comment]
Awesome - you want to discuss this off of here @hodlfinanceofficial on telegram

**Comment by rmshea** [comment]
sorry for the delay here, all -- we are rebuilding the ecosystem page and will have an update in the coming days.

**Comment by SolarDexOfficial** [comment]
Awesome looking forward to it
