### ISSUE TITLE
Add image in markdown

### ISSUE THREAD

**Issue by clintnetwork** [solana-labs/ecosystem#791]
Hi,

Does solana website support markdown images?

Thank you

**Comment by rmshea** [comment]
@clintnetwork yes!

**Comment by clintnetwork** [comment]
Ah good news :)

**Comment by clintnetwork** [comment]
Anyway @rmshea, I can read:
```
From DeFi and Web3 applications to games and NFTs, browse over 350 projects built on Solana.
```

But in tags, it seems that its more, is it dynamic?
